"""
Applies the frozen PROTOCOL.md exclusion cascade (section on "Exclusion
Cascade") in order, logs N surviving at every step, and writes
docs/exclusion_cascade_report.md + data/processed/eligible_records.csv
(the final surviving record list used by every downstream experiment).

Usage:
    python scripts/run_exclusion_cascade.py
"""
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

from preprocessing.ingestion import load_ctu_chb_record, load_clinical_metadata, record_path_for
from preprocessing.signal_processing import (
    NATIVE_FS, FHR_MIN, FHR_MAX, UC_MIN, UC_MAX,
    process_channel,
)

RAW_DIR = os.path.join(ROOT, "data", "raw", "ctu-chb-intrapartum-cardiotocography-database-1.0.0")
METADATA_PATH = os.path.join(ROOT, "data", "raw", "clinical_metadata.csv")
OUT_CSV = os.path.join(ROOT, "data", "processed", "eligible_records.csv")
OUT_REPORT = os.path.join(ROOT, "docs", "exclusion_cascade_report.md")

WINDOW_MINUTES = 30
WINDOW_SAMPLES = int(WINDOW_MINUTES * 60 * NATIVE_FS)  # 7200 at 4Hz
MIN_USABLE_MINUTES = 20


def final_window(signal: np.ndarray) -> np.ndarray:
    """Last-aligned final-30-min slice; shorter recordings yield a shorter slice."""
    if len(signal) >= WINDOW_SAMPLES:
        return signal[-WINDOW_SAMPLES:]
    return signal


def raw_missing_frac(signal_window: np.ndarray, lo: float, hi: float) -> float:
    if len(signal_window) == 0:
        return 1.0
    missing = (signal_window == 0.0) | (signal_window < lo) | (signal_window > hi)
    return float(missing.mean())


def main():
    metadata = load_clinical_metadata(METADATA_PATH)
    n_total = len(metadata)

    cascade = [("Total CTU-CHB records", n_total, list(metadata.index))]

    # --- Step 1: missing pH or BDecf -> drop ---
    has_ph = metadata["ph"].notna()
    has_bdecf = metadata["bdecf"].notna()
    step1_keep = metadata.index[has_ph & has_bdecf].tolist()
    cascade.append(("Step 1: has pH and BDecf", len(step1_keep), step1_keep))

    # --- Step 2: final-30-min FHR signal loss > 50% -> drop ---
    # --- Step 3: < 20 min usable trace after full gap/artifact chain -> drop ---
    step2_keep, step3_keep = [], []
    step2_dropped_ids, step3_dropped_ids = [], []
    load_failures = []

    for record_id in step1_keep:
        path = record_path_for(RAW_DIR, record_id)
        fhr, uc, fs = load_ctu_chb_record(path)
        if len(fhr) == 0:
            load_failures.append(record_id)
            continue

        fhr_win = final_window(fhr)
        uc_win = final_window(uc)

        # Step 2: raw missingness (pre-interpolation) on the FHR channel only,
        # per PROTOCOL.md ("FHR == 0").
        if raw_missing_frac(fhr_win, FHR_MIN, FHR_MAX) > 0.50:
            step2_dropped_ids.append(record_id)
            continue
        step2_keep.append(record_id)

        # Step 3: usable trace after the full gap/artifact chain.
        fhr_proc, fhr_missing = process_channel(fhr_win, FHR_MIN, FHR_MAX)
        usable_minutes = (~fhr_missing).sum() / NATIVE_FS / 60.0
        if usable_minutes < MIN_USABLE_MINUTES:
            step3_dropped_ids.append(record_id)
            continue
        step3_keep.append(record_id)

    cascade.append(("Step 2: final-30-min FHR signal loss <= 50%", len(step2_keep), step2_keep))
    cascade.append(("Step 3: >= 20 min usable trace after gap handling", len(step3_keep), step3_keep))

    # --- Write eligible_records.csv ---
    os.makedirs(os.path.dirname(OUT_CSV), exist_ok=True)
    eligible = metadata.loc[step3_keep].copy()
    eligible.to_csv(OUT_CSV)

    # --- Write report ---
    os.makedirs(os.path.dirname(OUT_REPORT), exist_ok=True)
    lines = [
        "# Exclusion Cascade Report",
        "",
        f"Generated by `scripts/run_exclusion_cascade.py`. Frozen rules: see `PROTOCOL.md`.",
        "",
        "| Step | N remaining | N dropped this step |",
        "|---|---|---|",
    ]
    prev_n = n_total
    for name, n, _ in cascade:
        dropped = prev_n - n
        lines.append(f"| {name} | {n} | {dropped if name != cascade[0][0] else '-'} |")
        prev_n = n

    lines += [
        "",
        f"**Final surviving N: {len(step3_keep)} of {n_total}** "
        f"({100*len(step3_keep)/n_total:.1f}%).",
        f"Plan's expected range: 430-480 of 552 (77.9-87.0%).",
        "",
    ]
    if load_failures:
        lines.append(f"- {len(load_failures)} record(s) failed to load (WFDB read error): {load_failures}")
    if step2_dropped_ids:
        lines.append(f"- {len(step2_dropped_ids)} dropped at Step 2 (signal loss > 50%): {step2_dropped_ids}")
    if step3_dropped_ids:
        lines.append(f"- {len(step3_dropped_ids)} dropped at Step 3 (< 20min usable): {step3_dropped_ids}")

    n_final = len(step3_keep)
    in_range = 430 <= n_final <= 480
    lines += [
        "",
        f"**In plan's expected range: {'YES' if in_range else 'NO -- deviation must be reported explicitly per PROTOCOL.md.'}**",
    ]

    with open(OUT_REPORT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print("\n".join(lines))
    print(f"\nWrote eligible_records.csv ({len(step3_keep)} rows) -> {OUT_CSV}")
    print(f"Wrote report -> {OUT_REPORT}")


if __name__ == "__main__":
    main()
